VPATH = /Users/admin/Downloads/gnu-debugger-6.8-src/gdb/testsuite/gdb.objc
srcdir = /Users/admin/Downloads/gnu-debugger-6.8-src/gdb/testsuite/gdb.objc

EXECUTABLES = basicclass

all: 
	@echo "Nothing to be done for all..."

info:
install-info:
dvi:
install:
uninstall: force
installcheck:
check:

clean mostlyclean:
	-rm -f *~ *.o *.ci
	-rm -f core ${EXECUTABLES}

distclean maintainer-clean realclean: clean
	-rm -f Makefile config.status config.log
